### ISSUE TITLE
Wiki or Mod Support?

### ISSUE THREAD

**Issue by O13SC3N3** [joshiejack/Progression#1]
Does this support modded items/blocks as well?

**Comment by joshiejack** [comment]
There's no wiki, the mod pretty much explains itself. Everyone that I've had try it out, was able to work it out. And I'm not sure which part you're referring to with mod support. In terms of recipes yes, in terms of generally yes. The only possible issue is with some mods and their autocrafting systems. Possibly giving ways around to bypass some of the crafting restrictions. AE is fine, because you have to craft the patterns for them manually anyways. And I'll combat, those as reports come in :P. And if you mean working with mod machines, and their recipes. That would be a lot of work, I would have to ASM a check in to every single mod out there. Mods don't naturally go, can this player craft this. I might do that eventually, but it'll still be an annoyance.

**Comment by O13SC3N3** [comment]
right on, best of luck to you m8.. Im gonna give it a shot in my next mudpack version.

**Comment by mindcloud69** [comment]
What about utilizing permissions to prevent interaction with certain mod items. This could give you a workaround until a better solution comes along.  Here is an example from Forge Essentials of some permission nodes that might be able to utilize to limit player actions as an example.

```
fe.protection.interact.tile.ToolForge                                                # INTERACT Tool Forge
fe.protection.interact.tile.ToolStation                                              # INTERACT tile.ToolStation.name
fe.protection.interact.tile.TravellersGear.armorstand                                # INTERACT Armor Stand
fe.protection.interact.tile.WorkbenchPlus                                            # INTERACT WorkbenchPlus
fe.protection.interact.tile.WrathCage                                                # INTERACT Wrath Cage
fe.protection.interact.tile.accumulationTable                                        # INTERACT Accumulation Table

fe.protection.interact.tile.appliedenergistics2.BlockCraftingMonitor                 # INTERACT Crafting Monitor
fe.protection.interact.tile.appliedenergistics2.BlockCraftingStorage                 # INTERACT 1k Crafting Storage
fe.protection.interact.tile.appliedenergistics2.BlockCraftingUnit                    # INTERACT Crafting Unit

fe.protection.inventory.Chisel                                                       # INVENTORY Chisel
fe.protection.inventory.exnihilo.crook                                               # INVENTORY Crook
```

**Comment by joshiejack** [comment]
I'd rather add support for things, than go 'you cannot use this block'. I already do stuff with ae and tinkers.
