### ISSUE TITLE
Somes questions 

### ISSUE THREAD

**Issue by Kahel3352** [joshiejack/Progression#19]
Hello, before all I really enjoy your mod, it looks very usefull. But there are some things I don't understand.

In the creative menu what the criteria items are used to? And how can I delete them?
The same with the "tile claimer" I don't understand what is it use for...

Also some criterias seem to be active even there is no criterias in the criteria tree (when I open the book). I just can't break grass block. 

Thanks to your time and your help.

**Comment by joshiejack** [comment]
The criteria items are items that you can give people, that will force complete the criteria instead of them having to complete it. They're cheat items essentially. You can't delete them. The tile claimer is only useful when you're playing a world that was created before the Progression mod was added. This is mostly for the Furnace at this point. Right clicking a furnace that was placed before the mod was installed, would mark it as belonging to you. So that you are able to smelt things that are unlocked using the furnace reward.

Huh, the only way that can happen is if you set a reward for being able to break a block... Then you can't break it, until it's unlocked.

**Comment by Kahel3352** [comment]
I think I understood the problem!
When I create a criteria in the default tab in the tree and I close the tree the criteria "disapear" and I can't access it anymore or delete it but it still active.  I don't know if it's a known bug or whatever.
(sorry to the "question" label, I did'nt know how to put it)

**Comment by Omuck3** [comment]
I have the same issue!
