### ISSUE TITLE
Cannot edit anything

### ISSUE THREAD

**Issue by ZigTheHedge** [joshiejack/Progression#24]
Hi there!
Am I really stupid, or just doing something wrong? I type "/progression edit" in chat, big black window opens, I click on "New", then double-click on criteria. Specifying the requirement (any really - it doesn't matter), specifying the result, renaming the criteria, right-clicking and... My criteria is absolutely blank as new, and named "New Criteria"... (single-player world, "progression" is the only mod active, forge 1388). Okay, second attempt - the same on a dedicated server: double-clicking the criteria, trying to set something up there, right-clicking out, and poof! Criteria is not even there anymore...
Progression version 0.4.1

**Comment by Omuck3** [comment]
Same issue!

**Comment by joshiejack** [comment]
Progression pretty much needs to be edited in singleplayer in 1.7.10. Because everytime you close the gui it would reload from the serversdata. I actually send the data from the client to the server in 1.8.9, so things shouldn't be such an issue. Plus the saving was rather buggy and didn't work like half the time in 1.7.10.
