### ISSUE TITLE
Ore Dictionary support 

### ISSUE THREAD

**Issue by longErste** [joshiejack/Progression#31]
I think it is important to support ore dictionary
Let's say that i want people to break logs after they have obtain some tools,  then I need to add all wood in minecraft. It would be cool to use ore:logwood as replacement

**Comment by joshiejack** [comment]
Progression in 1.8.9 instead of selecting individual items for anything uses a filter based system. So you'd be able to do such a thing. Even for rewards ^_^. Where there it would give a random item that fits in the filter, so if you filtered it to logwood it would give any random log. Of course can select a precise item still if you desire ^_^.
