### ISSUE TITLE
Minor Issues with Criteria

### ISSUE THREAD

**Issue by BLSK** [joshiejack/Progression#47]
I have been messing around with your mod in the modpack I have put together... I did run into an issue with the criteria just deleting it self in the most recent version.  I tried just repasting the criteria I had copied in another file to the old one and it isn't letting me into world which is strange as they were almost exactly alike.  It isn't giving me any real details but in case other have found this issue they may have more info if lucky, I am sorry I can't seem to dig up anything as it doesn't seem to have happened from what I have looked through but I do hope to try and catch it next time.  I didn't really notice it happening till a little over a week ago.

You remember when you changed the location of some stuff from Options to Criteria... Would it be possible to have the Progression Editor item moved to options?  From time to time the game just randomly crashing to menu it resets the Item selected in the criteria to the minecraft book which is ok but I was going to have an item from my mod with no use as of yet to harness the power of progression.

**Comment by joshiejack** [comment]
The 1.7 version is fairly buggy especially the newer versions and especially saving, i think people just ended up sticking with the 0.3 version. Honestly the 1.7 version was more of an experiment for me than anything. Ive rewritten a lot, and improved a bunch for the 1.8/1.9 version. I don't plan on backporting this to 1.7 mainly because a lot of the way things worked has been changed, such as you no longer picking items or locations but adding a bunch of filters, so you can have 1 thing that affects everything in say a mod, or ore dictionary etc, of course with normal item selection too. As well as a bunch of other things. I technically removed that option for using custom items to open the gui in the new versions too, but you would be able to recreate it with a criteria. Either way, I am done with the 1.7 version.

**Comment by BLSK** [comment]
Cool.  Looking forward to the update.  I am just waiting on the my full list to boost it to 1.9(as I hear 1.8 is somewhat being skipped).  As I have.  Once I get it updated I would gladly bring to your attention bugs I find.  Thanks for the fun mod :).

**Comment by joshiejack** [comment]
Yep fair enough ^_^
