### ISSUE TITLE
Thaumcraft's arcane crafting table is bypassing a crafting restriction

### ISSUE THREAD

**Issue by belathus** [joshiejack/Progression#64]
It seems that, even though we made a quest to stop players from crafting, say, an alchemical chest from Project E, Thaumcraft's arcane crafting table bypasses that restriction.

**Comment by joshiejack** [comment]
What version is this, due to the way i had to do things, i have to add the support for each crafting method. The other way i tried broke crafting for things that didn't have support. Felt it was better to have them bypass than be broken entirely. Thaumcraft should be supported in 1.8 though unless it broke somehow. If you have an idea for a better way to handle things would be great.

**Comment by belathus** [comment]
Minecraft 1.8.9, Thaumcraft version 5.2.4, Progression version 0.6.5. It may have broke. I'll ask around and see what I can find as far as suggestions go.

**Comment by joshiejack** [comment]
LOL, look what I did 
https://github.com/joshiejack/Progression/blob/1.8.9/src/main/java/joshie/progression/asm/ProgressionTransformer.java#L25

No wonder it broke xD

**Comment by belathus** [comment]
Hah!
